# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ff2a9d539d9333704c506f1ba0a90dc13f3fb07f4c18ad568e61c4a2afe09c588601db36c4ec9977080b37226917887ceac8b83e5f4382c3d335989133dc9c

test:
  secret_key_base: 7f491f024b99202ddbc899dd9d15df5c9300e4cb4b031479abb7cb4cb30c12d4b703a4750a1c6b739e130cdbcc39b9190cfd93ea11df36a5cb7efd734a7f2936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
